# %%
from pathlib import Path
import json, math
from datetime import timezone

import pandas as pd
import matplotlib.pyplot as plt

ROOT = Path("..").resolve() if Path.cwd().name == "notebooks" else Path.cwd()

# %%
# Snapshot generated by: python -m src.run_node kalshi_btc_edge --candle-days 3
edge = pd.read_csv(ROOT / "data/processed/kalshi_btc_edge.csv")
edge.head()

# %%
# What looks most mispriced right now?
edge["best_edge"] = edge[["edge_to_buy_yes", "edge_to_sell_yes"]].max(axis=1)
edge["side"] = edge["edge_to_buy_yes"].ge(edge["edge_to_sell_yes"]).map({True: "BUY_YES", False: "SELL_YES"})
edge.sort_values("best_edge", ascending=False).head(20)

# %%
ax = edge.sort_values("best_edge", ascending=False).head(30).plot.bar(
    x="ticker", y="best_edge", figsize=(12, 4), legend=False, title="Top Kalshi BTC theo edges"
)
ax.axhline(0, color="black", lw=1)
ax.set_ylabel("edge after crossing spread")
plt.tight_layout()

# %%
# Simple entry filter. This is NOT realized PnL yet; it is expected edge at the current snapshot.
MIN_EDGE = 0.03
trades = edge.query("best_edge >= @MIN_EDGE").copy()
trades["entry_price"] = trades["yes_ask"].where(trades["side"].eq("BUY_YES"), 1 - trades["yes_bid"])
trades["expected_pnl_per_contract"] = trades["best_edge"]
trades[["ticker", "side", "strike", "spot", "entry_price", "theo", "expected_pnl_per_contract", "volume"]].head(30)

# %%
trades["expected_pnl_per_contract"].describe()

# %%
# Historical-ish backtest from fetched Kalshi candlesticks.
# Strategy: at each candle close, buy YES if theo - yes_ask > threshold.
# If the market is settled, hold to settlement: YES pays settlement_value, NO pays 1 - settlement_value.

def load_json(path):
    return json.loads(path.read_text())

def norm_cdf(x):
    return 0.5 * math.erfc(-x / math.sqrt(2))

def binary_theo(spot, strike, expiry, now, vol):
    t = max((expiry - now).total_seconds(), 0) / (365 * 24 * 60 * 60)
    if t <= 0 or vol <= 0:
        return float(spot > strike)
    d2 = (math.log(spot / strike) - 0.5 * vol * vol * t) / (vol * math.sqrt(t))
    return norm_cdf(d2)

def realized_vol_annualized(closes):
    r = pd.Series(closes).astype(float).pipe(lambda s: (s / s.shift()).apply(math.log)).dropna()
    return r.std() * math.sqrt(365 * 24 * 60)

markets = []
for name in ["kxbtcd_open_markets.json", "kxbtcd_settled_markets.json"]:
    p = ROOT / "data/raw/kalshi" / name
    if p.exists():
        markets += load_json(p)
meta = pd.DataFrame(markets).drop_duplicates("ticker")
meta["close_time"] = pd.to_datetime(meta["close_time"], utc=True)
meta["settlement_value"] = pd.to_numeric(meta.get("settlement_value_dollars"), errors="coerce")
meta["strike"] = pd.to_numeric(meta["floor_strike"], errors="coerce")
meta = meta.set_index("ticker")

btc_raw = load_json(ROOT / "data/raw/candles/binance_BTC_1m.json")
btc = pd.DataFrame(btc_raw, columns=["open_ms", "open", "high", "low", "close", "volume", "close_ms", "qav", "n", "tbb", "tbq", "ignore"])
btc["ts"] = pd.to_datetime(btc["open_ms"], unit="ms", utc=True)
btc["spot"] = btc["close"].astype(float)
vol = realized_vol_annualized(btc["spot"].tail(240))
vol

# %%
rows = []
for p in (ROOT / "data/raw/kalshi/candles").glob("*_60m.json"):
    data = load_json(p)
    ticker = data.get("ticker")
    if ticker not in meta.index:
        continue
    m = meta.loc[ticker]
    for c in data.get("candlesticks", []):
        rows.append({
            "ticker": ticker,
            "ts": pd.to_datetime(c["end_period_ts"], unit="s", utc=True),
            "yes_bid": pd.to_numeric(c["yes_bid"].get("close_dollars"), errors="coerce"),
            "yes_ask": pd.to_numeric(c["yes_ask"].get("close_dollars"), errors="coerce"),
            "last": pd.to_numeric(c["price"].get("close_dollars"), errors="coerce"),
            "strike": m["strike"],
            "expiry": m["close_time"],
            "settlement_value": m["settlement_value"],
            "result": m.get("result", ""),
        })

kc = pd.DataFrame(rows).dropna(subset=["yes_bid", "yes_ask", "strike"])
if not kc.empty:
    kc = pd.merge_asof(kc.sort_values("ts"), btc[["ts", "spot"]].sort_values("ts"), on="ts", direction="nearest")
    kc["theo"] = [binary_theo(r.spot, r.strike, r.expiry, r.ts, vol) for r in kc.itertuples()]
    kc["buy_yes_edge"] = kc["theo"] - kc["yes_ask"]
    kc["buy_no_edge"] = (1 - kc["theo"]) - (1 - kc["yes_bid"])

kc.head()

# %%
# Realized PnL for settled markets only. One contract, hold to settlement, cross spread on entry.
THRESHOLD = 0.03
bt = kc.dropna(subset=["settlement_value"]).copy()
entries = []
for r in bt.itertuples():
    if r.buy_yes_edge >= THRESHOLD:
        entries.append({"ticker": r.ticker, "ts": r.ts, "side": "BUY_YES", "entry": r.yes_ask, "payout": r.settlement_value})
    if r.buy_no_edge >= THRESHOLD:
        entries.append({"ticker": r.ticker, "ts": r.ts, "side": "BUY_NO", "entry": 1 - r.yes_bid, "payout": 1 - r.settlement_value})

pnl = pd.DataFrame(entries)
if not pnl.empty:
    pnl["pnl"] = pnl["payout"] - pnl["entry"]
    pnl["cum_pnl"] = pnl["pnl"].cumsum()

pnl.head() if not pnl.empty else "No settled candle entries found. Fetch more/historical data."

# %%
if not pnl.empty:
    print(pnl["pnl"].describe())
    print("hit_rate", (pnl["pnl"] > 0).mean())
    print("total_pnl", pnl["pnl"].sum())
    pnl.plot(x="ts", y="cum_pnl", figsize=(10, 4), title=f"Naive hold-to-settlement PnL, threshold={THRESHOLD}")
    plt.axhline(0, color="black", lw=1)
    plt.tight_layout()

# %%
if not kc.empty:
    ax = kc.plot.scatter(x="theo", y="yes_ask", alpha=0.4, figsize=(5, 5), title="Kalshi YES ask vs model theo")
    ax.plot([0, 1], [0, 1], color="black", lw=1)
    plt.tight_layout()
